import asyncio
import re
from datetime import datetime, timezone, timedelta

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    ChatPermissions,
)
from telegram.ext import (
    ContextTypes,
    ApplicationHandlerStop,
)

from database import connect

from handlers.roles import get_rank_level

from handlers.moderation import (
    save_mute,
    save_restriction,
    save_ban,
    delete_restriction_record,
    mention_user,
    html_escape,
    parse_duration_token,
)


# ==================================================
# إعدادات عامة
# ==================================================

MIN_RANK_LEVEL = 4

LIST_1 = 1
LIST_2 = 2

BLOCKED_PERMISSION_MESSAGE = (
    "• هذا الأمر لـ نائب المالك وفوق فقط ."
)

RIYADH_TZ = timezone(
    timedelta(hours=3)
)


# ==================================================
# جلسات الإضافة / الحذف / إعداد العقوبة
# ==================================================

_blocked_sessions = {}


# ==================================================
# الصلاحيات
# ==================================================

def get_blocked_level(
    user_id,
    chat_id
):

    try:
        return int(
            get_rank_level(
                user_id,
                chat_id
            )
        )
    except TypeError:

        try:
            return int(
                get_rank_level(user_id)
            )
        except Exception:
            return 0

    except Exception:
        return 0


def can_manage_blocked_words(
    user_id,
    chat_id
):

    return (
        get_blocked_level(
            user_id,
            chat_id
        ) >= MIN_RANK_LEVEL
    )


# ==================================================
# قاعدة البيانات
# ==================================================

def ensure_blocked_words_tables():

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        # ==================================================
        # الكلمات
        #
        # list_id:
        # 1 = الكلمات المحظورة
        # 2 = الكلمات المحظورة2
        # ==================================================

        cur.execute("""
        CREATE TABLE IF NOT EXISTS blocked_words_v2
        (
            chat_id BIGINT NOT NULL,
            list_id INTEGER NOT NULL,
            word TEXT NOT NULL,

            PRIMARY KEY
            (
                chat_id,
                list_id,
                word
            )
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS
        idx_blocked_words_v2_lookup
        ON blocked_words_v2
        (
            chat_id,
            list_id
        )
        """)

        # ==================================================
        # إعدادات القوائم
        # ==================================================

        cur.execute("""
        CREATE TABLE IF NOT EXISTS blocked_words_settings_v2
        (
            chat_id BIGINT NOT NULL,
            list_id INTEGER NOT NULL,

            enabled INTEGER DEFAULT 0,

            action TEXT DEFAULT 'mute',
            duration INTEGER,

            warning_duration INTEGER,
            warning_action TEXT,
            warning_punishment_duration INTEGER,

            PRIMARY KEY
            (
                chat_id,
                list_id
            )
        )
        """)

        # ==================================================
        # الأشخاص الذين فتحوا القائمة من قبل
        # ==================================================

        cur.execute("""
        CREATE TABLE IF NOT EXISTS blocked_words_opened_v2
        (
            chat_id BIGINT NOT NULL,
            list_id INTEGER NOT NULL,
            user_id BIGINT NOT NULL,

            PRIMARY KEY
            (
                chat_id,
                list_id,
                user_id
            )
        )
        """)

        # ==================================================
        # إنذارات الكلمات المؤقتة
        # ==================================================

        cur.execute("""
        CREATE TABLE IF NOT EXISTS blocked_words_warnings_v2
        (
            chat_id BIGINT NOT NULL,
            list_id INTEGER NOT NULL,
            user_id BIGINT NOT NULL,

            warning_id BIGINT
            GENERATED BY DEFAULT AS IDENTITY
            PRIMARY KEY,

            expires_at BIGINT NOT NULL,
            created_at BIGINT NOT NULL
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS
        idx_blocked_words_warnings_lookup
        ON blocked_words_warnings_v2
        (
            chat_id,
            list_id,
            user_id
        )
        """)

        cur.execute("""
        CREATE INDEX IF NOT EXISTS
        idx_blocked_words_warnings_expiry
        ON blocked_words_warnings_v2
        (
            expires_at
        )
        """)

        # ==================================================
        # إنشاء إعدادات القائمتين
        # ==================================================

        cur.execute("""
        INSERT INTO blocked_words_settings_v2
        (
            chat_id,
            list_id
        )
        SELECT
            chat_id,
            1
        FROM blocked_words_settings
        ON CONFLICT
        (
            chat_id,
            list_id
        )
        DO NOTHING
        """)

        # ==================================================
        # نقل إعدادات النظام القديم للقائمة الأولى
        # ==================================================

        cur.execute("""
        UPDATE blocked_words_settings_v2 AS new
        SET
            enabled = old.enabled,
            action = old.action
        FROM blocked_words_settings AS old
        WHERE
            new.chat_id = old.chat_id
            AND new.list_id = 1
        """)

        # ==================================================
        # نقل الكلمات القديمة للقائمة الأولى
        # ==================================================

        cur.execute("""
        INSERT INTO blocked_words_v2
        (
            chat_id,
            list_id,
            word
        )
        SELECT
            chat_id,
            1,
            word
        FROM blocked_words
        ON CONFLICT
        (
            chat_id,
            list_id,
            word
        )
        DO NOTHING
        """)

        conn.commit()

    except Exception:

        conn.rollback()
        raise

    finally:

        if cur:
            cur.close()

        conn.close()


# ==================================================
# إعدادات افتراضية
# ==================================================

def ensure_list_settings(
    chat_id,
    list_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        INSERT INTO blocked_words_settings_v2
        (
            chat_id,
            list_id
        )
        VALUES
        (
            ?,
            ?
        )
        ON CONFLICT
        (
            chat_id,
            list_id
        )
        DO NOTHING
        """, (
            chat_id,
            list_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def get_settings(
    chat_id,
    list_id
):

    ensure_list_settings(
        chat_id,
        list_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        SELECT
            enabled,
            action,
            duration,
            warning_duration,
            warning_action,
            warning_punishment_duration
        FROM blocked_words_settings_v2
        WHERE
            chat_id=?
            AND list_id=?
        """, (
            chat_id,
            list_id
        ))

        row = cur.fetchone()

        if not row:

            return {
                "enabled": False,
                "action": "mute",
                "duration": None,
                "warning_duration": None,
                "warning_action": None,
                "warning_punishment_duration": None,
            }

        return {
            "enabled": bool(row[0]),
            "action": row[1] or "mute",
            "duration": row[2],
            "warning_duration": row[3],
            "warning_action": row[4],
            "warning_punishment_duration": row[5],
        }

    finally:

        if cur:
            cur.close()

        conn.close()


def set_enabled(
    chat_id,
    list_id,
    enabled
):

    ensure_list_settings(
        chat_id,
        list_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        UPDATE blocked_words_settings_v2
        SET enabled=?
        WHERE
            chat_id=?
            AND list_id=?
        """, (
            1 if enabled else 0,
            chat_id,
            list_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def set_direct_action(
    chat_id,
    list_id,
    action,
    duration
):

    ensure_list_settings(
        chat_id,
        list_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        UPDATE blocked_words_settings_v2
        SET
            action=?,
            duration=?
        WHERE
            chat_id=?
            AND list_id=?
        """, (
            action,
            duration,
            chat_id,
            list_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def set_warning_action(
    chat_id,
    list_id,
    warning_duration,
    warning_action,
    warning_punishment_duration
):

    ensure_list_settings(
        chat_id,
        list_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        UPDATE blocked_words_settings_v2
        SET
            action='warning',
            warning_duration=?,
            warning_action=?,
            warning_punishment_duration=?
        WHERE
            chat_id=?
            AND list_id=?
        """, (
            warning_duration,
            warning_action,
            warning_punishment_duration,
            chat_id,
            list_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


# ==================================================
# الكلمات
# ==================================================

def get_words(
    chat_id,
    list_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        SELECT word
        FROM blocked_words_v2
        WHERE
            chat_id=?
            AND list_id=?
        ORDER BY word
        """, (
            chat_id,
            list_id
        ))

        return [
            row[0]
            for row in cur.fetchall()
        ]

    finally:

        if cur:
            cur.close()

        conn.close()


def add_words(
    chat_id,
    list_id,
    words
):

    if not words:
        return

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        for word in words:

            cur.execute("""
            INSERT INTO blocked_words_v2
            (
                chat_id,
                list_id,
                word
            )
            VALUES
            (
                ?,
                ?,
                ?
            )
            ON CONFLICT
            (
                chat_id,
                list_id,
                word
            )
            DO NOTHING
            """, (
                chat_id,
                list_id,
                word
            ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def delete_words(
    chat_id,
    list_id,
    words
):

    if not words:
        return

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        for word in words:

            cur.execute("""
            DELETE FROM blocked_words_v2
            WHERE
                chat_id=?
                AND list_id=?
                AND word=?
            """, (
                chat_id,
                list_id,
                word
            ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


# ==================================================
# أول مرة يفتح فيها المشرف القائمة
# ==================================================

def was_opened_before(
    chat_id,
    list_id,
    user_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        SELECT 1
        FROM blocked_words_opened_v2
        WHERE
            chat_id=?
            AND list_id=?
            AND user_id=?
        LIMIT 1
        """, (
            chat_id,
            list_id,
            user_id
        ))

        return bool(cur.fetchone())

    finally:

        if cur:
            cur.close()

        conn.close()


def mark_opened(
    chat_id,
    list_id,
    user_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        INSERT INTO blocked_words_opened_v2
        (
            chat_id,
            list_id,
            user_id
        )
        VALUES
        (
            ?,
            ?,
            ?
        )
        ON CONFLICT
        (
            chat_id,
            list_id,
            user_id
        )
        DO NOTHING
        """, (
            chat_id,
            list_id,
            user_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


# ==================================================
# تنظيف الكلمة
# ==================================================

def normalize_word(word):

    word = (
        word
        .replace("\r", " ")
        .replace("\n", " ")
    )

    word = re.sub(
        r"\s+",
        " ",
        word
    )

    return word.strip()


def extract_input_words(text):

    if not text:
        return []

    result = []

    for line in text.splitlines():

        word = normalize_word(line)

        if not word:
            continue

        if word not in result:
            result.append(word)

    return result


# ==================================================
# مطابقة الكلمات
# ==================================================

def word_matches(
    text,
    word
):

    if not text or not word:
        return False

    word = normalize_word(word)

    if not word:
        return False

    escaped = re.escape(word)

    # --------------------------------------------------
    # \w في Python Unicode-aware
    #
    # لذلك:
    #
    # ياكلب😂       = يطابق
    # ياكلب ههههه   = يطابق
    # ياكلب…….      = يطابق
    #
    # ياكلبك        = لا يطابق
    # --------------------------------------------------

    pattern = (
        rf"(?<!\w)"
        rf"{escaped}"
        rf"(?!\w)"
    )

    return bool(
        re.search(
            pattern,
            text,
            flags=re.UNICODE
        )
    )


def find_blocked_word(
    text,
    words
):

    for word in words:

        if word_matches(
            text,
            word
        ):
            return word

    return None


# ==================================================
# الوقت
# ==================================================

def current_timestamp():

    return int(
        datetime.now(
            timezone.utc
        ).timestamp()
    )


def format_until(timestamp):

    if timestamp is None:
        return "لا توجد مدة"

    dt = datetime.fromtimestamp(
        timestamp,
        RIYADH_TZ
    )

    return dt.strftime(
        "%Y/%m/%d - %H:%M:%S"
    )


# ==================================================
# رسائل العقوبات
# ==================================================

def punishment_keyboard(
    action,
    chat_id,
    user_id
):

    action_ar = {
        "mute": "رفع الكتم ☑️",
        "restrict": "رفع القيود ☑️",
        "ban": "رفع الحظر ☑️",
    }

    return InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    action_ar[action],
                    callback_data=(
                        f"bw:lift:"
                        f"{action}:"
                        f"{chat_id}:"
                        f"{user_id}"
                    )
                )
            ]
        ]
    )


def punishment_message(
    action,
    target,
    until_timestamp
):

    mention = mention_user(
        target
    )

    if action == "mute":

        return (
            f"🔐 تَمَّ كتم {mention} "
            f"[{target.id}].\n"
            f"⏰ لمدة حتى: "
            f"{format_until(until_timestamp)}"
        )

    if action == "restrict":

        return (
            f"🔐 قُيِّدَ {mention} "
            f"[{target.id}].\n"
            f"⏰ لمدة حتى: "
            f"{format_until(until_timestamp)}"
        )

    return (
        f"🔐 تَمَّ حظر {mention} "
        f"[{target.id}].\n"
        f"⏰ لمدة حتى: "
        f"{format_until(until_timestamp)}"
    )


# ==================================================
# تنفيذ العقوبة
# ==================================================

async def apply_punishment(
    update,
    context,
    chat_id,
    target,
    action,
    duration
):

    until_timestamp = None

    if duration is not None:

        until_timestamp = (
            current_timestamp()
            + int(duration)
        )

    until_time = None

    if until_timestamp is not None:

        until_time = (
            datetime.fromtimestamp(
                until_timestamp,
                timezone.utc
            ).isoformat()
        )

    # ==================================================
    # الكتم
    # ==================================================

    if action == "mute":

        await asyncio.to_thread(
            save_mute,
            chat_id,
            target,
            until_time,
            None,
            context.bot.id
        )

    # ==================================================
    # التقييد
    # ==================================================

    elif action == "restrict":

        try:

            permissions = ChatPermissions(
                can_send_messages=False
            )

            await context.bot.restrict_chat_member(
                chat_id=chat_id,
                user_id=target.id,
                permissions=permissions,
                until_date=(
                    until_timestamp
                    if until_timestamp
                    else None
                )
            )

        except Exception as e:

            print(
                f"⚠️ فشل تقييد مستخدم بسبب كلمة محظورة: {e}"
            )

            return False

        await asyncio.to_thread(
            save_restriction,
            chat_id,
            target,
            until_time,
            None,
            context.bot.id
        )

    # ==================================================
    # الحظر
    # ==================================================

    elif action == "ban":

        try:

            await context.bot.ban_chat_member(
                chat_id=chat_id,
                user_id=target.id,
                until_date=(
                    until_timestamp
                    if until_timestamp
                    else None
                )
            )

        except Exception as e:

            print(
                f"⚠️ فشل حظر مستخدم بسبب كلمة محظورة: {e}"
            )

            return False

        await asyncio.to_thread(
            save_ban,
            chat_id,
            target,
            until_time,
            None,
            context.bot.id
        )

    else:

        return False

    if update and update.message:

        await update.message.reply_text(
            punishment_message(
                action,
                target,
                until_timestamp
            ),
            parse_mode="HTML",
            reply_markup=punishment_keyboard(
                action,
                chat_id,
                target.id
            )
        )

    return True


# ==================================================
# إنذارات الكلمات
# ==================================================

def cleanup_user_warnings(
    chat_id,
    list_id,
    user_id
):

    now = current_timestamp()

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        DELETE FROM blocked_words_warnings_v2
        WHERE
            chat_id=?
            AND list_id=?
            AND user_id=?
            AND expires_at<=?
        """, (
            chat_id,
            list_id,
            user_id,
            now
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def get_active_warning_count(
    chat_id,
    list_id,
    user_id
):

    cleanup_user_warnings(
        chat_id,
        list_id,
        user_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        SELECT COUNT(*)
        FROM blocked_words_warnings_v2
        WHERE
            chat_id=?
            AND list_id=?
            AND user_id=?
        """, (
            chat_id,
            list_id,
            user_id
        ))

        row = cur.fetchone()

        return int(
            row[0]
        ) if row else 0

    finally:

        if cur:
            cur.close()

        conn.close()


def add_blocked_warning(
    chat_id,
    list_id,
    user_id,
    duration
):

    now = current_timestamp()

    expires_at = (
        now + int(duration)
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        INSERT INTO blocked_words_warnings_v2
        (
            chat_id,
            list_id,
            user_id,
            expires_at,
            created_at
        )
        VALUES
        (
            ?,
            ?,
            ?,
            ?,
            ?
        )
        """, (
            chat_id,
            list_id,
            user_id,
            expires_at,
            now
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


def clear_blocked_warnings(
    chat_id,
    list_id,
    user_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute("""
        DELETE FROM blocked_words_warnings_v2
        WHERE
            chat_id=?
            AND list_id=?
            AND user_id=?
        """, (
            chat_id,
            list_id,
            user_id
        ))

        conn.commit()

    finally:

        if cur:
            cur.close()

        conn.close()


# ==================================================
# رسالة الإنذار
# ==================================================

async def send_blocked_warning(
    update,
    target,
    count
):

    await update.message.reply_text(
        "• كتب كلمة محظورة وجاه انذار .\n"
        f"• المستخدم ↤︎ {mention_user(target)}\n"
        f"• عدد إنذاراته ↤︎ {count}",
        parse_mode="HTML"
    )


# ==================================================
# تطبيق نظام الإنذار
# ==================================================

async def handle_warning_punishment(
    update,
    context,
    chat_id,
    list_id,
    target,
    settings
):

    warning_duration = (
        settings["warning_duration"]
    )

    warning_action = (
        settings["warning_action"]
    )

    punishment_duration = (
        settings["warning_punishment_duration"]
    )

    if not warning_duration:
        return

    if not warning_action:
        return

    await asyncio.to_thread(
        add_blocked_warning,
        chat_id,
        list_id,
        target.id,
        warning_duration
    )

    count = await asyncio.to_thread(
        get_active_warning_count,
        chat_id,
        list_id,
        target.id
    )

    # ==================================================
    # أول وثاني إنذار
    # ==================================================

    if count < 3:

        await send_blocked_warning(
            update,
            target,
            count
        )

        return

    # ==================================================
    # الإنذار الثالث
    #
    # لا توجد رسالة اختيار.
    # العقوبة تنفذ مباشرة.
    # ==================================================

    await asyncio.to_thread(
        clear_blocked_warnings,
        chat_id,
        list_id,
        target.id
    )

    await apply_punishment(
        update,
        context,
        chat_id,
        target,
        warning_action,
        punishment_duration
    )


# ==================================================
# عرض القائمة
# ==================================================

def list_title(
    list_id
):

    if list_id == LIST_1:
        return "قائمة الكلمات المحظورة"

    return "قائمة الكلمات المحظورة2"


def list_command_name(
    list_id
):

    if list_id == LIST_1:
        return "الكلمات المحظورة"

    return "الكلمات المحظورة2"


def build_list_message(
    chat_id,
    list_id
):

    words = get_words(
        chat_id,
        list_id
    )

    settings = get_settings(
        chat_id,
        list_id
    )

    title = list_title(
        list_id
    )

    if not words:

        text = (
            "لا توجد كلمات محظورة حاليًا ."
        )

    else:

        lines = [
            f"🚫 {title}:",
            ""
        ]

        for index, word in enumerate(
            words,
            1
        ):

            lines.append(
                f"{index} - {html_escape(word)}"
            )

        text = "\n".join(
            lines
        )

    status_text = (
        "الحالة: مفعلة 🟢"
        if settings["enabled"]
        else
        "الحالة: معطلة 🔴"
    )

    keyboard = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "اضافة كلمات ➕",
                    callback_data=(
                        f"bw:add:"
                        f"{list_id}:"
                        f"{chat_id}"
                    )
                ),
                InlineKeyboardButton(
                    "حذف كلمات 🗑️",
                    callback_data=(
                        f"bw:delete:"
                        f"{list_id}:"
                        f"{chat_id}"
                    )
                )
            ],
            [
                InlineKeyboardButton(
                    status_text,
                    callback_data=(
                        f"bw:toggle:"
                        f"{list_id}:"
                        f"{chat_id}"
                    )
                )
            ]
        ]
    )

    return text, keyboard


# ==================================================
# رسالة الترحيب لأول مرة
# ==================================================

def welcome_keyboard(
    chat_id,
    list_id
):

    return InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "هنا 👆🏻",
                    callback_data=(
                        f"bw:here:"
                        f"{list_id}:"
                        f"{chat_id}"
                    )
                ),
                InlineKeyboardButton(
                    "فتح القائمة بالخاص❕",
                    callback_data=(
                        f"bw:private:"
                        f"{list_id}:"
                        f"{chat_id}"
                    )
                )
            ]
        ]
    )


# ==================================================
# أمر القائمة
# ==================================================

async def blocked_words_command(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    actor = update.effective_user

    if not actor:
        return

    text = (
        update.message.text or ""
    ).strip()

    # ==================================================
    # تحديد القائمة
    # ==================================================

    list_id = None

    list_aliases = {
        "الكلمات المحظورة": 1,
        "الكلمات المحظورة/ه": 1,
        "الكلمات المحظورة2": 2,
        "الكلمات المحظورة/ه2": 2,
    }

    if text in list_aliases:

        list_id = list_aliases[text]

    else:

        # --------------------------------------------------
        # التفعيل والتعطيل
        # --------------------------------------------------

        action_match = re.fullmatch(
            r"(تفعيل|تعطيل)\s+"
            r"(الكلمات المحظورة|الكلمات المحظورة/ه|"
            r"الكلمات المحظورة2|الكلمات المحظورة/ه2)",
            text
        )

        if action_match:

            command_action = (
                action_match.group(1)
            )

            command_list = (
                action_match.group(2)
            )

            list_id = list_aliases[
                command_list
            ]

            chat = update.effective_chat

            if not chat:
                return

            if not can_manage_blocked_words(
                actor.id,
                chat.id
            ):

                await update.message.reply_text(
                    BLOCKED_PERMISSION_MESSAGE
                )

                raise ApplicationHandlerStop

            enabled = (
                command_action == "تفعيل"
            )

            await asyncio.to_thread(
                set_enabled,
                chat.id,
                list_id,
                enabled
            )

            if enabled:

                await update.message.reply_text(
                    "• تم تفعيل الكلمات المحظورة ✅ ."
                )

            else:

                await update.message.reply_text(
                    "• تم تعطيل الكلمات المحظورة ✅ ."
                )

            raise ApplicationHandlerStop

        # --------------------------------------------------
        # إعداد العقوبة
        # --------------------------------------------------

        punishment_match = re.fullmatch(
            r"ضع عقوبة\s+"
            r"(الكلمات المحظورة|الكلمات المحظورة/ه|"
            r"الكلمات المحظورة2|الكلمات المحظورة/ه2)"
            r"\s+"
            r"(كتم|تقييد|حظر|انذار)",
            text
        )

        if punishment_match:

            command_list = (
                punishment_match.group(1)
            )

            punishment = (
                punishment_match.group(2)
            )

            list_id = list_aliases[
                command_list
            ]

            chat = update.effective_chat

            if not chat:
                return

            if not can_manage_blocked_words(
                actor.id,
                chat.id
            ):

                await update.message.reply_text(
                    BLOCKED_PERMISSION_MESSAGE
                )

                raise ApplicationHandlerStop

            # ==================================================
            # الإنذار
            # ==================================================

            if punishment == "انذار":

                _blocked_sessions[
                    (
                        actor.id,
                        chat.id
                    )
                ] = {
                    "type": "warning_setup",
                    "list_id": list_id,
                }

                await update.message.reply_text(
                    "تمام، أرسل مدة الانذار+ العقوبة الي بعد "
                    "الانذارات مع المدة بهذي الطريقة:\n\n"
                    "3د كتم 5ي"
                )

                raise ApplicationHandlerStop

            # ==================================================
            # الحظر دائم
            # ==================================================

            if punishment == "حظر":

                await asyncio.to_thread(
                    set_direct_action,
                    chat.id,
                    list_id,
                    "ban",
                    None
                )

                await update.message.reply_text(
                    "• تم وضع عقوبة الحظر على الكلمات المحظورة "
                    "بنجاح ✅ ."
                )

                raise ApplicationHandlerStop

            # ==================================================
            # الكتم / التقييد
            # ==================================================

            action = (
                "mute"
                if punishment == "كتم"
                else "restrict"
            )

            _blocked_sessions[
                (
                    actor.id,
                    chat.id
                )
            ] = {
                "type": "direct_duration",
                "list_id": list_id,
                "action": action,
            }

            if action == "mute":

                await update.message.reply_text(
                    "• حسنًا اختر مدة الكتم ."
                )

            else:

                await update.message.reply_text(
                    "• حسنًا اختر مدة التقييد ."
                )

            raise ApplicationHandlerStop

        return

    # ==================================================
    # يجب أن يكون داخل قروب أو خاص
    # ==================================================

    chat = update.effective_chat

    if not chat:
        return

    # ==================================================
    # الصلاحية
    # ==================================================

    if chat.type in (
        "group",
        "supergroup"
    ):

        if not can_manage_blocked_words(
            actor.id,
            chat.id
        ):

            await update.message.reply_text(
                BLOCKED_PERMISSION_MESSAGE
            )

            raise ApplicationHandlerStop

        # ==================================================
        # أول مرة
        # ==================================================

        opened = await asyncio.to_thread(
            was_opened_before,
            chat.id,
            list_id,
            actor.id
        )

        await asyncio.to_thread(
            mark_opened,
            chat.id,
            list_id,
            actor.id
        )

        if not opened:

            mention = (
                f'<a href="tg://user?id={actor.id}">'
                f'{html_escape(actor.first_name or "المشرف")}'
                f'</a>'
            )

            await update.message.reply_text(
                f"اهلًا يالمشرف {mention}",
                parse_mode="HTML",
                reply_markup=welcome_keyboard(
                    chat.id,
                    list_id
                )
            )

            raise ApplicationHandlerStop

        message_text, keyboard = await asyncio.to_thread(
            build_list_message,
            chat.id,
            list_id
        )

        await update.message.reply_text(
            message_text,
            parse_mode="HTML",
            reply_markup=keyboard
        )

        raise ApplicationHandlerStop

    # ==================================================
    # الخاص
    # ==================================================

    if chat.type == "private":

        message_text, keyboard = await asyncio.to_thread(
            build_list_message,
            chat.id,
            list_id
        )

        await update.message.reply_text(
            message_text,
            parse_mode="HTML",
            reply_markup=keyboard
        )

        raise ApplicationHandlerStop


# ==================================================
# جلسات الإدخال
# ==================================================

async def handle_blocked_session(
    update,
    context
):

    if not update.message:
        return False

    actor = update.effective_user

    if not actor:
        return False

    chat = update.effective_chat

    if not chat:
        return False

    key = (
        actor.id,
        chat.id
    )

    session = _blocked_sessions.get(
        key
    )

    if not session:
        return False

    # ==================================================
    # الصلاحية
    # ==================================================

    origin_chat_id = chat.id

    if not can_manage_blocked_words(
        actor.id,
        origin_chat_id
    ):

        _blocked_sessions.pop(
            key,
            None
        )

        await update.message.reply_text(
            BLOCKED_PERMISSION_MESSAGE
        )

        return True

    # ==================================================
    # إضافة كلمات
    # ==================================================

    if session["type"] == "add":

        words = extract_input_words(
            update.message.text or ""
        )

        list_id = session["list_id"]

        if not words:

            await update.message.reply_text(
                "• لم يتم العثور على كلمات لإضافتها ."
            )

            return True

        await asyncio.to_thread(
            add_words,
            origin_chat_id,
            list_id,
            words
        )

        _blocked_sessions.pop(
            key,
            None
        )

        try:
            await update.message.delete()
        except Exception:
            pass

        await update.message.reply_text(
            "تم حفظ الكلمات بنجاح ✅ .",
            reply_markup=InlineKeyboardMarkup(
                [
                    [
                        InlineKeyboardButton(
                            "↩️ رجوع لقائمة الكلمات",
                            callback_data=(
                                f"bw:back:"
                                f"{list_id}:"
                                f"{origin_chat_id}"
                            )
                        ),
                        InlineKeyboardButton(
                            "اغلاق القائمة",
                            callback_data=(
                                f"bw:close:"
                                f"{origin_chat_id}"
                            )
                        )
                    ]
                ]
            )
        )

        return True

    # ==================================================
    # حذف كلمات
    # ==================================================

    if session["type"] == "delete":

        words = extract_input_words(
            update.message.text or ""
        )

        list_id = session["list_id"]

        if not words:

            await update.message.reply_text(
                "• لم يتم العثور على كلمات لحذفها ."
            )

            return True

        await asyncio.to_thread(
            delete_words,
            origin_chat_id,
            list_id,
            words
        )

        _blocked_sessions.pop(
            key,
            None
        )

        try:
            await update.message.delete()
        except Exception:
            pass

        await update.message.reply_text(
            "تم حذف الكلمات بنجاح ✅ .",
            reply_markup=InlineKeyboardMarkup(
                [
                    [
                        InlineKeyboardButton(
                            "↩️ رجوع لقائمة الكلمات",
                            callback_data=(
                                f"bw:back:"
                                f"{list_id}:"
                                f"{origin_chat_id}"
                            )
                        ),
                        InlineKeyboardButton(
                            "اغلاق القائمة",
                            callback_data=(
                                f"bw:close:"
                                f"{origin_chat_id}"
                            )
                        )
                    ]
                ]
            )
        )

        return True

    # ==================================================
    # مدة العقوبة المباشرة
    # ==================================================

    if session["type"] == "direct_duration":

        token = (
            update.message.text or ""
        ).strip()

        duration = parse_duration_token(
            token
        )

        if duration is None:

            await update.message.reply_text(
                "• المدة غير صحيحة .\n"
                "• مثال: 5ي أو 30ث أو 50د أو 1س"
            )

            return True

        await asyncio.to_thread(
            set_direct_action,
            origin_chat_id,
            session["list_id"],
            session["action"],
            duration
        )

        _blocked_sessions.pop(
            key,
            None
        )

        await update.message.reply_text(
            "• تم حفظ إعداد العقوبة بنجاح ✅ ."
        )

        return True

    # ==================================================
    # إعداد الإنذار
    # ==================================================

    if session["type"] == "warning_setup":

        parts = (
            update.message.text or ""
        ).strip().split()

        if len(parts) not in (2, 3):

            await update.message.reply_text(
                "• الصيغة غير صحيحة .\n\n"
                "مثال:\n"
                "3د كتم 5ي"
            )

            return True

        warning_duration = parse_duration_token(
            parts[0]
        )

        if warning_duration is None:

            await update.message.reply_text(
                "• مدة الانذار غير صحيحة .\n\n"
                "مثال:\n"
                "3د كتم 5ي"
            )

            return True

        punishment_word = parts[1]

        punishment_map = {
            "كتم": "mute",
            "تقييد": "restrict",
            "حظر": "ban",
        }

        warning_action = punishment_map.get(
            punishment_word
        )

        if not warning_action:

            await update.message.reply_text(
                "• العقوبة غير صحيحة .\n\n"
                "استخدم: كتم أو تقييد أو حظر"
            )

            return True

        punishment_duration = None

        if warning_action in (
            "mute",
            "restrict"
        ):

            if len(parts) != 3:

                await update.message.reply_text(
                    "• يجب كتابة مدة العقوبة أيضًا .\n\n"
                    "مثال:\n"
                    "3د كتم 5ي"
                )

                return True

            punishment_duration = parse_duration_token(
                parts[2]
            )

            if punishment_duration is None:

                await update.message.reply_text(
                    "• مدة العقوبة غير صحيحة .\n\n"
                    "مثال:\n"
                    "3د كتم 5ي"
                )

                return True

        else:

            if len(parts) != 2:

                await update.message.reply_text(
                    "• الحظر دائم، اكتبها هكذا:\n\n"
                    "3د حظر"
                )

                return True

        await asyncio.to_thread(
            set_warning_action,
            origin_chat_id,
            session["list_id"],
            warning_duration,
            warning_action,
            punishment_duration
        )

        _blocked_sessions.pop(
            key,
            None
        )

        await update.message.reply_text(
            "• تم حفظ إعدادات الانذار بنجاح ✅ ."
        )

        return True

    return False


# ==================================================
# فحص الكلمات
# ==================================================

async def check_blocked_words(
    update,
    context
):

    if not update.message:
        return False

    if not update.effective_chat:
        return False

    # الكلمات المحظورة في القروبات فقط
    if update.effective_chat.type not in (
        "group",
        "supergroup"
    ):
        return False

    actor = update.effective_user

    if not actor:
        return False

    text = (
        update.message.text or ""
    )

    if not text:
        return False

    chat_id = (
        update.effective_chat.id
    )

    # ==================================================
    # القائمة الأولى والثانية
    # ==================================================

    for list_id in (
        LIST_1,
        LIST_2
    ):

        settings = await asyncio.to_thread(
            get_settings,
            chat_id,
            list_id
        )

        if not settings["enabled"]:
            continue

        words = await asyncio.to_thread(
            get_words,
            chat_id,
            list_id
        )

        if not words:
            continue

        matched = find_blocked_word(
            text,
            words
        )

        if not matched:
            continue

        # ==================================================
        # حفظ المستخدم
        # ==================================================

        try:

            from handlers.moderation import (
                save_target_user
            )

            await asyncio.to_thread(
                save_target_user,
                actor
            )

        except Exception:
            pass

        # ==================================================
        # عقوبة مباشرة
        # ==================================================

        if settings["action"] in (
            "mute",
            "restrict",
            "ban"
        ):

            duration = settings[
                "duration"
            ]

            await apply_punishment(
                update,
                context,
                chat_id,
                actor,
                settings["action"],
                duration
            )

            return True

        # ==================================================
        # عقوبة الإنذار
        # ==================================================

        if settings["action"] == "warning":

            await handle_warning_punishment(
                update,
                context,
                chat_id,
                list_id,
                actor,
                settings
            )

            return True

    return False


# ==================================================
# الراوتر الرئيسي للرسائل
# ==================================================

async def blocked_words_message_handler(
    update,
    context
):

    if not update.message:
        return

    actor = update.effective_user

    if not actor:
        return

    # ==================================================
    # جلسة إضافة / حذف / إعداد
    # ==================================================

    handled = await handle_blocked_session(
        update,
        context
    )

    if handled:

        raise ApplicationHandlerStop

    # ==================================================
    # أوامر القائمتين
    # ==================================================

    text = (
        update.message.text or ""
    ).strip()

    command_names = {
        "الكلمات المحظورة",
        "الكلمات المحظورة/ه",
        "الكلمات المحظورة2",
        "الكلمات المحظورة/ه2",
    }

    is_punishment_command = bool(
        re.fullmatch(
            r"ضع عقوبة\s+"
            r"(الكلمات المحظورة|الكلمات المحظورة/ه|"
            r"الكلمات المحظورة2|الكلمات المحظورة/ه2)"
            r"\s+"
            r"(كتم|تقييد|حظر|انذار)",
            text
        )
    )

    is_toggle_command = bool(
        re.fullmatch(
            r"(تفعيل|تعطيل)\s+"
            r"(الكلمات المحظورة|الكلمات المحظورة/ه|"
            r"الكلمات المحظورة2|الكلمات المحظورة/ه2)",
            text
        )
    )

    if (
        text in command_names
        or is_punishment_command
        or is_toggle_command
    ):

        await blocked_words_command(
            update,
            context
        )

        raise ApplicationHandlerStop

    # ==================================================
    # فحص الكلمات
    # ==================================================

    matched = await check_blocked_words(
        update,
        context
    )

    if matched:

        raise ApplicationHandlerStop


# ==================================================
# أزرار القائمة
# ==================================================

async def blocked_words_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    query = update.callback_query

    if not query:
        return

    data = (
        query.data or ""
    )

    if not data.startswith(
        "bw:"
    ):
        return

    actor = query.from_user

    if not actor:
        return

    parts = data.split(":")

    if len(parts) < 2:
        return

    action = parts[1]

    # ==================================================
    # تحديد القائمة
    # ==================================================

    list_id = None
    origin_chat_id = None

    if action in (
        "here",
        "private",
        "add",
        "delete",
        "toggle",
        "back"
    ):

        if len(parts) != 4:
            await query.answer()
            return

        try:

            list_id = int(
                parts[2]
            )

            origin_chat_id = int(
                parts[3]
            )

        except Exception:

            await query.answer()
            return

    elif action == "close":

        if len(parts) != 3:

            await query.answer()
            return

        try:
            origin_chat_id = int(
                parts[2]
            )
        except Exception:
            await query.answer()
            return

    elif action == "lift":

        if len(parts) != 5:

            await query.answer()
            return

        punishment_action = parts[2]

        try:

            origin_chat_id = int(
                parts[3]
            )

            target_id = int(
                parts[4]
            )

        except Exception:

            await query.answer()
            return

        list_id = None

    else:

        await query.answer()
        return

    # ==================================================
    # صلاحية القوائم
    # ==================================================

    if not can_manage_blocked_words(
        actor.id,
        origin_chat_id
    ):

        await query.answer(
            BLOCKED_PERMISSION_MESSAGE,
            show_alert=True
        )

        return

    # ==================================================
    # هنا
    # ==================================================

    if action == "here":

        await query.answer()

        if not query.message:
            return

        text, keyboard = await asyncio.to_thread(
            build_list_message,
            origin_chat_id,
            list_id
        )

        await query.edit_message_text(
            text,
            parse_mode="HTML",
            reply_markup=keyboard
        )

        return

    # ==================================================
    # الخاص
    # ==================================================

    if action == "private":

        await query.answer()

        if not query.message:
            return

        text, keyboard = await asyncio.to_thread(
            build_list_message,
            origin_chat_id,
            list_id
        )

        try:

            await context.bot.send_message(
                chat_id=actor.id,
                text=text,
                parse_mode="HTML",
                reply_markup=keyboard
            )

            await query.edit_message_text(
                "تم الإرسال بالخاص ✅ ."
            )

        except Exception as e:

            print(
                f"⚠️ تعذر إرسال قائمة الكلمات بالخاص: {e}"
            )

            await query.edit_message_text(
                "تعذر إرسال القائمة بالخاص."
            )

        return

    # ==================================================
    # إضافة
    # ==================================================

    if action == "add":

        await query.answer()

        if not query.message:
            return

        # --------------------------------------------------
        # جلسة الإدخال تكون في نفس المحادثة التي ضغط منها
        # --------------------------------------------------

        session_chat_id = (
            query.message.chat.id
        )

        _blocked_sessions[
            (
                actor.id,
                session_chat_id
            )
        ] = {
            "type": "add",
            "list_id": list_id,
            "origin_chat_id": origin_chat_id,
        }

        await query.edit_message_text(
            "• حسنًا ارسل الكلمات التي تريد إضافتها .\n\n"
            "مثال:\n\n"
            "كلزق\n"
            "كلتبن\n"
            "ياكلب\n"
            "الخ…"
        )

        return

    # ==================================================
    # حذف
    # ==================================================

    if action == "delete":

        await query.answer()

        if not query.message:
            return

        session_chat_id = (
            query.message.chat.id
        )

        _blocked_sessions[
            (
                actor.id,
                session_chat_id
            )
        ] = {
            "type": "delete",
            "list_id": list_id,
            "origin_chat_id": origin_chat_id,
        }

        await query.edit_message_text(
            "• حسنًا ارسل الكلمات التي تريد حذفها .\n\n"
            "مثال:\n\n"
            "كلزق\n"
            "كلتبن\n"
            "ياكلب\n"
            "الخ…"
        )

        return

    # ==================================================
    # التفعيل / التعطيل
    # ==================================================

    if action == "toggle":

        settings = await asyncio.to_thread(
            get_settings,
            origin_chat_id,
            list_id
        )

        new_status = not settings[
            "enabled"
        ]

        await asyncio.to_thread(
            set_enabled,
            origin_chat_id,
            list_id,
            new_status
        )

        await query.answer(
            "تم تفعيل القائمة ✅"
            if new_status
            else
            "تم تعطيل القائمة ✅"
        )

        if not query.message:
            return

        text, keyboard = await asyncio.to_thread(
            build_list_message,
            origin_chat_id,
            list_id
        )

        await query.edit_message_text(
            text,
            parse_mode="HTML",
            reply_markup=keyboard
        )

        return

    # ==================================================
    # رجوع
    # ==================================================

    if action == "back":

        await query.answer()

        if not query.message:
            return

        text, keyboard = await asyncio.to_thread(
            build_list_message,
            origin_chat_id,
            list_id
        )

        await query.edit_message_text(
            text,
            parse_mode="HTML",
            reply_markup=keyboard
        )

        return

    # ==================================================
    # إغلاق
    # ==================================================

    if action == "close":

        await query.answer()

        if query.message:

            try:
                await query.message.delete()
            except Exception:
                pass

        return

    # ==================================================
    # رفع العقوبة
    # ==================================================

    if action == "lift":

        await query.answer()

        target = None

        try:

            chat_member = await context.bot.get_chat_member(
                origin_chat_id,
                target_id
            )

            target = chat_member.user

        except Exception:

            class StoredUser:
                pass

            target = StoredUser()
            target.id = target_id
            target.username = None
            target.first_name = str(
                target_id
            )

        # ==================================================
        # رفع الكتم
        # ==================================================

        if punishment_action == "mute":

            await asyncio.to_thread(
                delete_restriction_record,
                "bot_mutes",
                origin_chat_id,
                target_id
            )

        # ==================================================
        # رفع التقييد
        # ==================================================

        elif punishment_action == "restrict":

            try:

                permissions = ChatPermissions(
                    can_send_messages=True,
                    can_send_audios=True,
                    can_send_documents=True,
                    can_send_photos=True,
                    can_send_videos=True,
                    can_send_video_notes=True,
                    can_send_voice_notes=True,
                    can_send_polls=True,
                    can_send_other_messages=True,
                    can_add_web_page_previews=True,
                    can_invite_users=True,
                    can_manage_topics=True,
                )

                await context.bot.restrict_chat_member(
                    chat_id=origin_chat_id,
                    user_id=target_id,
                    permissions=permissions
                )

            except Exception as e:

                print(
                    f"⚠️ فشل رفع القيود: {e}"
                )

            await asyncio.to_thread(
                delete_restriction_record,
                "restrictions",
                origin_chat_id,
                target_id
            )

        # ==================================================
        # رفع الحظر
        # ==================================================

        elif punishment_action == "ban":

            try:

                await context.bot.unban_chat_member(
                    chat_id=origin_chat_id,
                    user_id=target_id,
                    only_if_banned=False
                )

            except Exception as e:

                print(
                    f"⚠️ فشل رفع الحظر: {e}"
                )

            await asyncio.to_thread(
                delete_restriction_record,
                "moderation_bans",
                origin_chat_id,
                target_id
            )

        if query.message:

            try:
                await query.edit_message_reply_markup(
                    reply_markup=None
                )
            except Exception:
                pass

        return


# ==================================================
# انتهاء مدة إنذارات الكلمات
# ==================================================

async def blocked_words_expiry_loop(
    application
):

    while True:

        try:

            now = current_timestamp()

            conn = connect()
            cur = None

            try:

                cur = conn.cursor()

                cur.execute("""
                DELETE FROM blocked_words_warnings_v2
                WHERE expires_at<=?
                """, (
                    now,
                ))

                conn.commit()

            finally:

                if cur:
                    cur.close()

                conn.close()

        except Exception as e:

            print(
                f"⚠️ خطأ في انتهاء إنذارات الكلمات المحظورة: {e}"
            )

        await asyncio.sleep(5)
