import asyncio
import html
import re
from urllib.parse import urlparse

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ChatMemberStatus, ChatType, ParseMode
from telegram.error import TelegramError
from telegram.ext import ContextTypes, ApplicationHandlerStop

from config import OWNER_ID
from database import connect, acquire_schema_lock


# الأوامر التي يدير بها المالك والمطورون النظام
MANAGEMENT_PATTERN = re.compile(
    r"^(?:ضع اجباري\s+.+|حذف اجباري\s+.+|مسح الاجباري|عرض الاجباري|الاجباري|تفعيل الاجباري|تعطيل الاجباري)$"
)
START_ALIASES = {"بدء البوت", "ابدأ البوت", "تشغيل البوت بالخاص"}


def ensure_mandatory_subscription_tables():
    conn = connect()
    cur = conn.cursor()
    try:
        acquire_schema_lock(conn)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS mandatory_subscription_settings (
                chat_id BIGINT PRIMARY KEY,
                enabled INTEGER NOT NULL DEFAULT 0,
                updated_by BIGINT,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS mandatory_subscription_requirements (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                group_id BIGINT NOT NULL,
                requirement_type TEXT NOT NULL,
                target_chat_id BIGINT,
                target TEXT NOT NULL,
                title TEXT NOT NULL,
                join_url TEXT NOT NULL,
                UNIQUE(group_id, requirement_type, target)
            )
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_mandatory_subscription_group
            ON mandatory_subscription_requirements(group_id)
        """)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        conn.close()


def _db_fetchone(query, params=()):
    conn = connect()
    cur = conn.cursor()
    try:
        cur.execute(query, params)
        return cur.fetchone()
    finally:
        cur.close()
        conn.close()


def _db_fetchall(query, params=()):
    conn = connect()
    cur = conn.cursor()
    try:
        cur.execute(query, params)
        return cur.fetchall()
    finally:
        cur.close()
        conn.close()


def _is_developer_sync(user_id):
    if not user_id:
        return False
    if user_id == OWNER_ID:
        return True
    # نفس مصدر صلاحية المطورين المستخدم في لوحة المطور الحالية.
    conn = connect()
    cur = conn.cursor()
    try:
        cur.execute(
            "SELECT 1 FROM developer_panel_access WHERE user_id=? LIMIT 1",
            (user_id,),
        )
        return cur.fetchone() is not None
    except Exception:
        # إذا لم يكن جدول لوحة المطور موجودًا أو حدث خطأ، لا نمنح صلاحية.
        return False
    finally:
        cur.close()
        conn.close()


async def _is_manager(user_id):
    return await asyncio.to_thread(_is_developer_sync, user_id)


def _save_requirement_sync(group_id, req_type, target_chat_id, target, title, join_url):
    conn = connect()
    cur = conn.cursor()
    try:
        if req_type == "start":
            # شرط واحد لبدء البوت في كل مجموعة.
            cur.execute(
                "DELETE FROM mandatory_subscription_requirements WHERE group_id=? AND requirement_type='start'",
                (group_id,),
            )
        cur.execute("""
            INSERT INTO mandatory_subscription_requirements
                (group_id, requirement_type, target_chat_id, target, title, join_url)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT (group_id, requirement_type, target)
            DO UPDATE SET target_chat_id=EXCLUDED.target_chat_id,
                          title=EXCLUDED.title,
                          join_url=EXCLUDED.join_url
        """, (group_id, req_type, target_chat_id, target, title, join_url))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        conn.close()


def _remove_requirement_sync(group_id, req_type, target=None):
    conn = connect()
    cur = conn.cursor()
    try:
        if req_type == "start":
            cur.execute(
                "DELETE FROM mandatory_subscription_requirements WHERE group_id=? AND requirement_type='start'",
                (group_id,),
            )
        else:
            cur.execute(
                "DELETE FROM mandatory_subscription_requirements WHERE group_id=? AND requirement_type='chat' AND target=?",
                (group_id, target),
            )
        count = cur.rowcount
        conn.commit()
        return count
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        conn.close()


def _set_enabled_sync(group_id, enabled, user_id):
    conn = connect()
    cur = conn.cursor()
    try:
        cur.execute("""
            INSERT INTO mandatory_subscription_settings(chat_id, enabled, updated_by, updated_at)
            VALUES (?, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(chat_id)
            DO UPDATE SET enabled=EXCLUDED.enabled,
                          updated_by=EXCLUDED.updated_by,
                          updated_at=CURRENT_TIMESTAMP
        """, (group_id, int(enabled), user_id))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        conn.close()


def _get_group_config_sync(group_id):
    settings = _db_fetchone(
        "SELECT enabled FROM mandatory_subscription_settings WHERE chat_id=?",
        (group_id,),
    )
    rows = _db_fetchall("""
        SELECT id, requirement_type, target_chat_id, target, title, join_url
        FROM mandatory_subscription_requirements
        WHERE group_id=?
        ORDER BY id
    """, (group_id,))
    return bool(settings and settings[0]), rows


def _private_start_exists_sync(user_id):
    # track_private_start الموجود في main.py يسجل /start في هذا الجدول بالفعل.
    try:
        return _db_fetchone(
            "SELECT 1 FROM developer_private_starts WHERE user_id=? LIMIT 1",
            (user_id,),
        ) is not None
    except Exception:
        return False


def _parse_public_telegram_target(value):
    """إرجاع username من @username أو رابط t.me العام؛ لا يقبل روابط الدعوة الخاصة."""
    value = value.strip()
    if value.startswith("@"): 
        username = value[1:]
        return username if re.fullmatch(r"[A-Za-z0-9_]{5,32}", username) else None
    if value.startswith("https://") or value.startswith("http://"):
        parsed = urlparse(value)
        if parsed.netloc.lower() not in {"t.me", "www.t.me", "telegram.me", "www.telegram.me"}:
            return None
        path = parsed.path.strip("/")
        if not path or path.startswith("+") or path.startswith("joinchat/"):
            return None
        username = path.split("/")[0]
        if username.lower() in {"share", "proxy", "addstickers", "iv"}:
            return None
        return username if re.fullmatch(r"[A-Za-z0-9_]{5,32}", username) else None
    return None


def _is_member_status(member):
    status = getattr(member, "status", None)
    if status in (ChatMemberStatus.CREATOR, ChatMemberStatus.ADMINISTRATOR, ChatMemberStatus.MEMBER):
        return True
    if status == ChatMemberStatus.RESTRICTED:
        return bool(getattr(member, "is_member", False))
    return False


async def _check_requirement(context, user_id, req):
    # tuple: id, type, target_chat_id, target, title, join_url
    _rid, req_type, target_chat_id, _target, _title, _join_url = req
    if req_type == "start":
        return await asyncio.to_thread(_private_start_exists_sync, user_id)
    if req_type != "chat" or target_chat_id is None:
        return False
    try:
        member = await context.bot.get_chat_member(
            chat_id=int(target_chat_id),
            user_id=user_id,
        )
        return _is_member_status(member)
    except TelegramError as exc:
        # الفشل في التحقق لا يعني أن المستخدم مشترك؛ نبقي الشرط مطلوبًا.
        print(f"⚠️ تعذر التحقق من الاشتراك الإجباري في {target_chat_id}: {exc}")
        return False


def _escape(value):
    return html.escape(str(value or ""), quote=True)


async def mandatory_subscription_guard(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = update.effective_message
    chat = update.effective_chat
    user = update.effective_user
    if not message or not chat or chat.type not in (ChatType.GROUP, ChatType.SUPERGROUP):
        return
    if not user or user.is_bot or user.id == 8453977662:
    return
    # لا نعترض رسائل أحداث المجموعة، مثل دخول عضو جديد.
    if message.new_chat_members or message.left_chat_member or message.group_chat_created or message.supergroup_chat_created or message.channel_chat_created:
        return
    text = message.text or message.caption or ""
    if text and MANAGEMENT_PATTERN.fullmatch(text.strip()):
        # نترك أوامر إدارة النظام تصل إلى معالجها؛ هو الذي يتحقق من الصلاحية.
        return

    try:
        enabled, requirements = await asyncio.to_thread(_get_group_config_sync, chat.id)
    except Exception as exc:
        print(f"⚠️ تعذر قراءة إعدادات الاشتراك الإجباري: {exc}")
        return  # خطأ قاعدة البيانات لا ينبغي أن يعطّل المجموعة بالكامل.
    if not enabled or not requirements:
        return

    missing = []
    for req in requirements:
        if not await _check_requirement(context, user.id, req):
            missing.append(req)
    if not missing:
        return

    try:
        await message.delete()
    except TelegramError as exc:
        print(f"⚠️ تعذر حذف رسالة غير المستوفي للشروط: {exc}")

    name = user.first_name or user.username or "مستخدم"
    lines = [
        f"• يالامير ~ <a href=\"tg://user?id={user.id}\">{_escape(name)}</a>",
        "مايمديك ترسل أي رسالة هنا لازم تستوفي الشروط تحت ⚠️",
        "تأكد أنك مستوفي الشروط التالية:",
    ]
    buttons = []
    bot_username = context.bot_data.get("mandatory_bot_username")
    if any(req[1] == "start" for req in missing) and not bot_username:
        try:
            me = await context.bot.get_me()
            bot_username = me.username
            context.bot_data["mandatory_bot_username"] = bot_username
        except TelegramError:
            bot_username = None

    for req in missing:
        _rid, req_type, _target_chat_id, _target, title, join_url = req
        lines.append(f"• {_escape(title)}")
        if req_type == "start":
            url = f"https://t.me/{bot_username}?start=mandatory" if bot_username else None
            label = "افتح البوت واضغط ابدأ"
        else:
            url = join_url
            label = f"اشترك في {title}"
        if url:
            buttons.append([InlineKeyboardButton(label[:64], url=url)])

    try:
        await context.bot.send_message(
            chat_id=chat.id,
            text="\n".join(lines),
            parse_mode=ParseMode.HTML,
            reply_markup=InlineKeyboardMarkup(buttons) if buttons else None,
            disable_web_page_preview=True,
        )
    except TelegramError as exc:
        print(f"⚠️ تعذر إرسال تنبيه الاشتراك الإجباري: {exc}")

    # يمنع بقية معالجات الرسالة المحذوفة من تنفيذ أوامر أو احتساب نقاط.
    raise ApplicationHandlerStop


async def mandatory_subscription_commands(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = update.effective_message
    chat = update.effective_chat
    user = update.effective_user
    if not message or not chat or not user:
        return
    text = (message.text or "").strip()
    if not MANAGEMENT_PATTERN.fullmatch(text):
        return
    if not await _is_manager(user.id):
        await message.reply_text("• هذا الأمر للمالك والمطورين فقط.")
        raise ApplicationHandlerStop

    if text == "تفعيل الاجباري":
        _enabled, requirements = await asyncio.to_thread(_get_group_config_sync, chat.id)
        if not requirements:
            await message.reply_text(
                "• ما أضفت أي شرط حتى الآن.\n"
                "أضف قناة/قروب بكتابة: ضع اجباري @username\n"
                "أو أضف شرط بدء البوت: ضع اجباري بدء البوت"
            )
            raise ApplicationHandlerStop
        await asyncio.to_thread(_set_enabled_sync, chat.id, True, user.id)
        await message.reply_text("• تم تفعيل الاشتراك الإجباري في هذه المجموعة.")
        raise ApplicationHandlerStop

    if text == "تعطيل الاجباري":
        await asyncio.to_thread(_set_enabled_sync, chat.id, False, user.id)
        await message.reply_text("• تم تعطيل الاشتراك الإجباري في هذه المجموعة.")
        raise ApplicationHandlerStop

    if text in ("عرض الاجباري", "الاجباري"):
        enabled, requirements = await asyncio.to_thread(_get_group_config_sync, chat.id)
        status = "مفعّل" if enabled else "معطّل"
        lines = [f"• حالة الاشتراك الإجباري: {status}", "", "الشروط المسجلة:"]
        if not requirements:
            lines.append("• ما فيه شروط مضافة.")
        for i, req in enumerate(requirements, 1):
            _rid, req_type, _target_chat_id, target, title, _join_url = req
            lines.append(f"{i}. {title}" + (" (بدء البوت بالخاص)" if req_type == "start" else f" — {target}"))
        lines.append("\nلإضافة شرط: ضع اجباري @username أو ضع اجباري بدء البوت")
        lines.append("لحذف شرط: حذف اجباري @username أو حذف اجباري بدء البوت")
        await message.reply_text("\n".join(lines))
        raise ApplicationHandlerStop

    if text == "مسح الاجباري":
        conn = connect()
        cur = conn.cursor()
        try:
            cur.execute("DELETE FROM mandatory_subscription_requirements WHERE group_id=?", (chat.id,))
            cur.execute("UPDATE mandatory_subscription_settings SET enabled=0, updated_by=?, updated_at=CURRENT_TIMESTAMP WHERE chat_id=?", (user.id, chat.id))
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            cur.close()
            conn.close()
        await message.reply_text("• تم حذف جميع شروط الاشتراك الإجباري وتعطيله في هذه المجموعة.")
        raise ApplicationHandlerStop

    if text.startswith("حذف اجباري "):
        value = text[len("حذف اجباري "):].strip()
        if value in START_ALIASES:
            count = await asyncio.to_thread(_remove_requirement_sync, chat.id, "start")
        else:
            username = _parse_public_telegram_target(value)
            target = "@" + username if username else value
            count = await asyncio.to_thread(_remove_requirement_sync, chat.id, "chat", target)
        await message.reply_text("• تم حذف الشرط." if count else "• ما لقيت هذا الشرط ضمن الشروط المسجلة.")
        raise ApplicationHandlerStop

    if text.startswith("ضع اجباري "):
        value = text[len("ضع اجباري "):].strip()
        if value in START_ALIASES:
            await asyncio.to_thread(
                _save_requirement_sync,
                chat.id, "start", None, "start", "بدء البوت في الخاص", "https://t.me/"
            )
            await message.reply_text(
                "• تمت إضافة شرط بدء البوت.\n"
                "أي شخص ما سبق أرسل /start للبوت لازم يفتحه ويضغط ابدأ."
            )
            raise ApplicationHandlerStop

        # يدعم @username أو رابط t.me العام، وكذلك chat_id رقمي مع رابط دعوة خاص اختياري.
        parts = value.split(maxsplit=1)
        target_value = parts[0]
        custom_url = parts[1].strip() if len(parts) == 2 else None
        username = _parse_public_telegram_target(target_value)
        chat_identifier = ("@" + username) if username else target_value
        if not username and not re.fullmatch(r"-?\d{5,20}", chat_identifier):
            await message.reply_text(
                "• ما قدرت أتحقق من هذا الهدف.\n"
                "استخدم @username لقناة/قروب عام، أو ارسل آيدي القناة/القروب ثم رابط الدعوة الخاص.\n"
                "روابط الدعوة الخاصة وحدها لا تسمح للبوت بمعرفة القروب للتحقق من العضوية."
            )
            raise ApplicationHandlerStop
        try:
            target_chat = await context.bot.get_chat(chat_identifier)
        except TelegramError as exc:
            await message.reply_text(
                "• ما قدرت أوصل للقناة/القروب. تأكد أن اليوزر أو الآيدي صحيح، وأن البوت مضاف للمكان ومشرف فيه.\n"
                "التفاصيل: " + _escape(str(exc))
            , parse_mode=ParseMode.HTML)
            raise ApplicationHandlerStop

        if target_chat.type not in (ChatType.CHANNEL, ChatType.GROUP, ChatType.SUPERGROUP):
            await message.reply_text("• الهدف لازم يكون قناة أو قروب تيليجرام، مو حساب شخصي.")
            raise ApplicationHandlerStop
        if custom_url:
            parsed = urlparse(custom_url)
            if parsed.scheme not in ("https", "http") or not parsed.netloc:
                await message.reply_text("• رابط الدعوة غير صحيح.")
                raise ApplicationHandlerStop
            join_url = custom_url
        elif target_chat.username:
            join_url = f"https://t.me/{target_chat.username}"
        else:
            await message.reply_text(
                "• هذه قناة/مجموعة خاصة. استخدم الصيغة التالية مع رابط الدعوة:\n"
                "ضع اجباري -1001234567890 https://t.me/+رابط_الدعوة"
            )
            raise ApplicationHandlerStop

        title = target_chat.title or ("@" + target_chat.username if target_chat.username else str(target_chat.id))
        stored_target = "@" + target_chat.username if target_chat.username else str(target_chat.id)
        await asyncio.to_thread(
            _save_requirement_sync,
            chat.id, "chat", target_chat.id, stored_target, title, join_url
        )
        await message.reply_text(
            f"• تمت إضافة شرط الاشتراك في <b>{_escape(title)}</b>.\n"
            "تأكد أن البوت مشرف في القناة/القروب حتى يقدر يتحقق من العضوية."
            , parse_mode=ParseMode.HTML
        )
        raise ApplicationHandlerStop
