import asyncio
import re

from collections import defaultdict, deque
from datetime import datetime, timezone

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    ChatPermissions,
)

from telegram.ext import ContextTypes

from database import connect

from handlers.roles import (
    OWNER_ID,
    get_rank_level,
    is_primary_developer,
    RANK_LEVELS,
)

from handlers.moderation import (
    save_mute,
    save_restriction,
    save_ban,
    mention_user,
)


# ==================================================
# الإعدادات
# ==================================================

DEFAULT_LIMIT = 3
DEFAULT_SECONDS = 5

DEFAULT_PUNISHMENT_DURATION = 300

MAX_MESSAGES_MEMORY = 50


# ==================================================
# جلسات إعداد التكرار
#
# المفتاح:
# (chat_id, user_id)
# ==================================================

repetition_sessions = {}


# ==================================================
# كاش الرسائل
#
# chat_id -> user_id -> deque
#
# نحفظ:
# (message_id, timestamp)
# ==================================================

_repetition_messages = defaultdict(
    lambda: defaultdict(
        lambda: deque(
            maxlen=MAX_MESSAGES_MEMORY
        )
    )
)


# ==================================================
# كاش إعدادات التكرار
#
# chat_id -> settings
# ==================================================

_repetition_settings_cache = {}

_repetition_settings_cache_lock = None


def _get_settings_cache_lock():
    global _repetition_settings_cache_lock

    if _repetition_settings_cache_lock is None:
        _repetition_settings_cache_lock = asyncio.Lock()

    return _repetition_settings_cache_lock


def _invalidate_repetition_settings_cache(chat_id):
    _repetition_settings_cache.pop(
        chat_id,
        None
    )


# ==================================================
# إنشاء جداول التكرار
# ==================================================

def create_repetition_tables():

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        # --------------------------------------------------
        # إعدادات التكرار القديمة التي ما زالت مستخدمة
        # --------------------------------------------------

        columns = {
            "repetition_punishment_duration": (
                "INTEGER DEFAULT 300"
            ),
            "repetition_rank": (
                "TEXT DEFAULT 'عضو'"
            ),
        }

        for column, definition in columns.items():

            cur.execute(
                f"""
                ALTER TABLE protection_settings
                ADD COLUMN IF NOT EXISTS {column} {definition}
                """
            )

        # --------------------------------------------------
        # جدول الإنذارات الجديد موجود في database.py
        #
        # warnings:
        # chat_id
        # user_id
        # warning_id
        # source
        # created_at
        #
        # لا ننشئ جدول repetition_warnings الجديد
        # لأن الإنذارات اليدوية والتكرار أصبحت في نفس الجدول.
        # --------------------------------------------------

        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS warnings
            (
                chat_id BIGINT NOT NULL,
                user_id BIGINT NOT NULL,
                warning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source TEXT NOT NULL DEFAULT 'manual',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_warnings_user
            ON warnings
            (
                chat_id,
                user_id
            )
            """
        )

        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_warnings_created
            ON warnings
            (
                chat_id,
                user_id,
                created_at
            )
            """
        )

        conn.commit()

    except Exception as e:

        try:
            conn.rollback()
        except Exception:
            pass

        print(
            "❌ خطأ في إنشاء جداول التكرار:",
            e
        )

        raise

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()


# ==================================================
# إنشاء إعدادات المجموعة إذا لم تكن موجودة
# ==================================================

def ensure_repetition_settings(chat_id):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            """
            INSERT INTO protection_settings
            (
                chat_id,
                repetition_enabled,
                repetition_limit,
                repetition_seconds,
                repetition_action,
                repetition_punishment_duration,
                repetition_rank
            )
            VALUES (?, 0, ?, ?, 'mute', ?, 'عضو')
            ON CONFLICT(chat_id)
            DO NOTHING
            """,
            (
                chat_id,
                DEFAULT_LIMIT,
                DEFAULT_SECONDS,
                DEFAULT_PUNISHMENT_DURATION,
            )
        )

        conn.commit()

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()


# ==================================================
# جلب إعدادات التكرار
# ==================================================

def get_repetition_settings(chat_id):

    cached = _repetition_settings_cache.get(
        chat_id
    )

    if cached is not None:
        return cached.copy()

    ensure_repetition_settings(
        chat_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            """
            SELECT
                repetition_enabled,
                repetition_limit,
                repetition_seconds,
                repetition_action,
                repetition_punishment_duration,
                repetition_rank
            FROM protection_settings
            WHERE chat_id=?
            """,
            (
                chat_id,
            )
        )

        row = cur.fetchone()

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()

    if not row:

        settings = {
            "enabled": False,
            "limit": DEFAULT_LIMIT,
            "seconds": DEFAULT_SECONDS,
            "action": "mute",
            "punishment_duration": DEFAULT_PUNISHMENT_DURATION,
            "rank": "عضو",
        }

    else:

        settings = {
            "enabled": bool(row[0]),

            "limit": max(
                1,
                int(
                    row[1]
                    or DEFAULT_LIMIT
                )
            ),

            "seconds": max(
                1,
                int(
                    row[2]
                    or DEFAULT_SECONDS
                )
            ),

            "action": (
                row[3]
                if row[3] in (
                    "mute",
                    "restrict",
                    "ban",
                )
                else "mute"
            ),

            "punishment_duration": max(
                1,
                int(
                    row[4]
                    or DEFAULT_PUNISHMENT_DURATION
                )
            ),

            "rank": (
                row[5]
                if row[5] in RANK_LEVELS
                else "عضو"
            ),
        }

    _repetition_settings_cache[
        chat_id
    ] = settings.copy()

    return settings


# ==================================================
# تحديث إعداد
# ==================================================

def update_repetition_setting(
    chat_id,
    column,
    value
):

    allowed_columns = {
        "repetition_enabled",
        "repetition_limit",
        "repetition_seconds",
        "repetition_action",
        "repetition_punishment_duration",
        "repetition_rank",
    }

    if column not in allowed_columns:

        raise ValueError(
            "Invalid repetition setting"
        )

    ensure_repetition_settings(
        chat_id
    )

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            f"""
            UPDATE protection_settings
            SET {column}=?
            WHERE chat_id=?
            """,
            (
                value,
                chat_id,
            )
        )

        conn.commit()

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()

    _invalidate_repetition_settings_cache(
        chat_id
    )


# ==================================================
# تحويل المدة
# ==================================================

DURATION_PATTERN = re.compile(
    r"^\s*(\d+(?:\.\d+)?)\s*"
    r"(ث|ثانية|ثواني|د|دقيقة|دقائق|س|ساعة|ساعات|ي|يوم|أيام)"
    r"\s*$"
)


def parse_duration_token(token):

    if not token:
        return None

    match = DURATION_PATTERN.match(
        str(token)
    )

    if not match:
        return None

    try:

        number = float(
            match.group(1)
        )

    except Exception:

        return None

    if number < 1:
        return None

    unit = match.group(2)

    if unit in (
        "ث",
        "ثانية",
        "ثواني",
    ):

        multiplier = 1

    elif unit in (
        "د",
        "دقيقة",
        "دقائق",
    ):

        multiplier = 60

    elif unit in (
        "س",
        "ساعة",
        "ساعات",
    ):

        multiplier = 3600

    else:

        multiplier = 86400

    seconds = int(
        number * multiplier
    )

    if seconds < 1:
        return None

    return seconds


# ==================================================
# تنسيق المدة
# ==================================================

def format_duration(seconds):

    seconds = int(seconds)

    if seconds % 86400 == 0:

        value = seconds // 86400

        return f"{value} يوم"

    if seconds % 3600 == 0:

        value = seconds // 3600

        return f"{value} ساعة"

    if seconds % 60 == 0:

        value = seconds // 60

        return f"{value} دقيقة"

    return f"{seconds} ثانية"


# ==================================================
# هل الرتبة مستهدفة؟
# ==================================================

def repetition_rank_allowed(
    user_id,
    chat_id,
    selected_rank
):

    if user_id == OWNER_ID:
        return False

    if is_primary_developer(
        user_id
    ):
        return False

    if selected_rank not in RANK_LEVELS:
        selected_rank = "عضو"

    try:

        level = get_rank_level(
            user_id,
            chat_id
        )

    except TypeError:

        level = get_rank_level(
            user_id
        )

    except Exception:

        return False

    selected_level = RANK_LEVELS[
        selected_rank
    ]

    return (
        level <= selected_level
    )


# ==================================================
# تنظيف الرسائل القديمة من الكاش
# ==================================================

def cleanup_user_messages(
    chat_id,
    user_id,
    seconds
):

    now = datetime.now(
        timezone.utc
    )

    messages = _repetition_messages[
        chat_id
    ][
        user_id
    ]

    while messages:

        _, created_at = messages[0]

        age = (
            now - created_at
        ).total_seconds()

        if age <= seconds:
            break

        messages.popleft()


# ==================================================
# إضافة رسالة
# ==================================================

def add_repetition_message(
    chat_id,
    user_id,
    message_id,
    seconds
):

    cleanup_user_messages(
        chat_id,
        user_id,
        seconds
    )

    messages = _repetition_messages[
        chat_id
    ][
        user_id
    ]

    now = datetime.now(
        timezone.utc
    )

    messages.append(
        (
            message_id,
            now
        )
    )

    return list(messages)


# ==================================================
# جلب آخر N رسائل
# ==================================================

def get_last_repetition_messages(
    chat_id,
    user_id,
    limit
):

    messages = _repetition_messages[
        chat_id
    ][
        user_id
    ]

    if not messages:
        return []

    return [
        message_id
        for message_id, _ in list(
            messages
        )[-limit:]
    ]


# ==================================================
# تصفير عداد المستخدم
# ==================================================

def reset_repetition_messages(
    chat_id,
    user_id
):

    try:

        _repetition_messages[
            chat_id
        ].pop(
            user_id,
            None
        )

    except Exception:
        pass


# ==================================================
# حذف رسائل التكرار
# ==================================================

async def delete_repetition_messages(
    bot,
    chat_id,
    message_ids
):

    if not message_ids:
        return

    async def delete_one(message_id):

        try:

            await bot.delete_message(
                chat_id=chat_id,
                message_id=message_id
            )

        except Exception:
            pass

    await asyncio.gather(
        *[
            delete_one(message_id)
            for message_id in message_ids
        ],
        return_exceptions=True
    )


# ==================================================
# عدد جميع الإنذارات
#
# يشمل:
# - الإنذارات اليدوية
# - إنذارات التكرار
#
# ولا توجد مدة للإنذار.
# ==================================================

def get_warning_count(
    chat_id,
    user_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            """
            SELECT COUNT(*)
            FROM warnings
            WHERE chat_id=?
            AND user_id=?
            """,
            (
                chat_id,
                user_id,
            )
        )

        row = cur.fetchone()

        return int(
            row[0] or 0
        )

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()


# ==================================================
# إضافة إنذار تكرار
#
# لا توجد مدة.
# ==================================================

def add_warning(
    chat_id,
    user_id,
    duration=None
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            """
            INSERT INTO warnings
            (
                chat_id,
                user_id,
                source
            )
            VALUES (?, ?, ?)
            """,
            (
                chat_id,
                user_id,
                "repetition",
            )
        )

        conn.commit()

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()


# ==================================================
# مسح تحذيرات المستخدم
# ==================================================

def clear_warnings(
    chat_id,
    user_id
):

    conn = connect()
    cur = None

    try:

        cur = conn.cursor()

        cur.execute(
            """
            DELETE FROM warnings
            WHERE chat_id=?
            AND user_id=?
            """,
            (
                chat_id,
                user_id,
            )
        )

        deleted = cur.rowcount

        conn.commit()

        return int(
            deleted or 0
        )

    finally:

        if cur is not None:

            try:
                cur.close()
            except Exception:
                pass

        conn.close()


# ==================================================
# أسماء العقوبات
# ==================================================

ACTION_NAMES = {
    "mute": "كتم",
    "restrict": "تقييد",
    "ban": "حظر",
}


# ==================================================
# صلاحية إعدادات التكرار
#
# ادمن اساسي وفوق
# ==================================================

def can_manage_repetition(
    user_id,
    chat_id
):

    if user_id == OWNER_ID:
        return True

    if is_primary_developer(
        user_id
    ):
        return True

    try:

        return (
            get_rank_level(
                user_id,
                chat_id
            ) >= 3
        )

    except TypeError:

        return (
            get_rank_level(
                user_id
            ) >= 3
        )

    except Exception:

        return False


# ==================================================
# منشن حقيقي
# ==================================================

def _user_mention(user):

    name = (
        getattr(
            user,
            "first_name",
            None
        )
        or getattr(
            user,
            "full_name",
            None
        )
        or "المستخدم"
    )

    return (
        f'<a href="tg://user?id={user.id}">'
        f'{name}'
        f'</a>'
    )


# ==================================================
# تنفيذ عقوبة التكرار
#
# العقوبة يتم اختيارها يدويًا من زر:
# كتم / تقييد
# ==================================================

async def punish_user(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    user,
    action,
    punishment_duration
):

    if not update.effective_chat:
        return False

    chat_id = update.effective_chat.id

    now = int(
        datetime.now(
            timezone.utc
        ).timestamp()
    )

    until_timestamp = None

    if (
        action in (
            "mute",
            "restrict",
        )
        and punishment_duration
    ):

        until_timestamp = (
            now + int(
                punishment_duration
            )
        )

    until_time = None

    if until_timestamp is not None:

        until_time = datetime.fromtimestamp(
            until_timestamp,
            timezone.utc
        ).isoformat()

    # ==================================================
    # الكتم
    # ==================================================

    if action == "mute":

        try:

            await asyncio.to_thread(
                save_mute,
                chat_id,
                user,
                until_time,
                "التكرار",
                context.bot.id
            )

        except Exception as e:

            print(
                f"❌ خطأ في كتم التكرار: {e}"
            )

            return False

        return True

    # ==================================================
    # التقييد
    # ==================================================

    if action == "restrict":

        try:

            permissions = ChatPermissions(
                can_send_messages=False
            )

            await context.bot.restrict_chat_member(
                chat_id=chat_id,
                user_id=user.id,
                permissions=permissions,
                until_date=until_timestamp
            )

            await asyncio.to_thread(
                save_restriction,
                chat_id,
                user,
                until_time,
                "التكرار",
                context.bot.id
            )

        except Exception as e:

            print(
                f"❌ خطأ في تقييد التكرار: {e}"
            )

            return False

        return True

    return False


# ==================================================
# رسالة الإنذار الثالث
# ==================================================

async def send_third_warning_message(
    context,
    chat_id,
    user,
    warning_count
):

    mention = _user_mention(
        user
    )

    keyboard = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "تقييد",
                    callback_data=(
                        f"repetition_punish:restrict:{user.id}"
                    )
                ),
                InlineKeyboardButton(
                    "كتم",
                    callback_data=(
                        f"repetition_punish:mute:{user.id}"
                    )
                ),
            ]
        ]
    )

    await context.bot.send_message(
        chat_id=chat_id,
        text=(
            f"• المستخدم ↤︎ {mention}\n"
            f"• وصلت إنذاراته : {warning_count}\n"
            "اختر العقوبة المناسبة له:"
        ),
        reply_markup=keyboard,
        parse_mode="HTML"
    )


# ==================================================
# معالجة التكرار
# ==================================================

async def repetition_message_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    message = update.effective_message
    user = update.effective_user
    chat = update.effective_chat

    if not message:
        return

    if not user:
        return

    if not chat:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    # ==================================================
    # تجاهل رسائل الخدمة
    # ==================================================

    if (
        message.new_chat_members
        or message.left_chat_member
        or message.new_chat_title
        or message.new_chat_photo
        or message.delete_chat_photo
        or message.group_chat_created
        or message.supergroup_chat_created
        or message.channel_chat_created
        or message.migrate_to_chat_id
        or message.migrate_from_chat_id
    ):
        return

    # ==================================================
    # تجاهل أوامر /
    # ==================================================

    if (
        message.text
        and message.text.startswith("/")
    ):
        return

    if (
        message.caption
        and message.caption.startswith("/")
    ):
        return

    # ==================================================
    # إعدادات التكرار
    # ==================================================

    try:

        settings = get_repetition_settings(
            chat.id
        )

    except Exception as e:

        print(
            "❌ خطأ في جلب إعدادات التكرار:",
            e
        )

        return

    if not settings["enabled"]:
        return

    # ==================================================
    # رتبة المستخدم
    # ==================================================

    try:

        allowed = repetition_rank_allowed(
            user.id,
            chat.id,
            settings["rank"]
        )

    except Exception as e:

        print(
            "❌ خطأ في تحديد رتبة التكرار:",
            e
        )

        return

    if not allowed:
        return

    # ==================================================
    # إضافة الرسالة
    # ==================================================

    try:

        messages = add_repetition_message(
            chat.id,
            user.id,
            message.message_id,
            settings["seconds"]
        )

    except Exception as e:

        print(
            "❌ خطأ في إضافة رسالة التكرار:",
            e
        )

        return

    if len(messages) < settings["limit"]:
        return

    # ==================================================
    # اكتشاف التكرار
    # ==================================================

    print(
        f"🔁 تكرار مكتشف | "
        f"chat={chat.id} | "
        f"user={user.id} | "
        f"count={len(messages)} | "
        f"limit={settings['limit']} | "
        f"seconds={settings['seconds']}"
    )

    # ==================================================
    # حذف آخر N رسائل
    # ==================================================

    message_ids = get_last_repetition_messages(
        chat.id,
        user.id,
        settings["limit"]
    )

    await delete_repetition_messages(
        context.bot,
        chat.id,
        message_ids
    )

    # ==================================================
    # تصفير عداد الرسائل
    # ==================================================

    reset_repetition_messages(
        chat.id,
        user.id
    )

    # ==================================================
    # جلب عدد الإنذارات
    #
    # نفس العداد للإنذارات اليدوية والتكرار.
    # ==================================================

    try:

        warning_count = get_warning_count(
            chat.id,
            user.id
        )

    except Exception as e:

        print(
            "❌ خطأ في جلب الإنذارات:",
            e
        )

        return

    # ==================================================
    # إضافة إنذار جديد
    # ==================================================

    try:

        add_warning(
            chat.id,
            user.id
        )

    except Exception as e:

        print(
            "❌ خطأ في إضافة إنذار التكرار:",
            e
        )

        return

    new_warning_count = (
        warning_count + 1
    )

    # ==================================================
    # الإنذار الثالث وما بعده
    #
    # لا يتم تطبيق العقوبة تلقائيًا.
    # ==================================================

    if new_warning_count >= 3:

        try:

            await send_third_warning_message(
                context,
                chat.id,
                user,
                new_warning_count
            )

        except Exception as e:

            print(
                "❌ خطأ في إرسال اختيار العقوبة:",
                e
            )

        return

    # ==================================================
    # الإنذار الأول / الثاني
    # ==================================================

    mention = _user_mention(
        user
    )

    try:

        await context.bot.send_message(
            chat_id=chat.id,
            text=(
                f"⚠️ تحذير التكرار {new_warning_count}/3\n\n"
                f"المستخدم ↤︎ {mention}"
            ),
            parse_mode="HTML"
        )

    except Exception as e:

        print(
            "❌ خطأ في إرسال تحذير التكرار:",
            e
        )


# ==================================================
# Callback اختيار عقوبة الإنذار الثالث
#
# repetition_punish:restrict:user_id
# repetition_punish:mute:user_id
# ==================================================

async def repetition_action_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    query = update.callback_query

    if not query:
        return

    actor = query.from_user

    if not actor:
        return

    message = query.message

    if not message:
        return

    chat = message.chat

    if not chat:
        return

    data = query.data or ""

    # ==================================================
    # السماح فقط للـ callback الجديد
    # ==================================================

    if not data.startswith(
        "repetition_punish:"
    ):

        # توافق مع أي callback قديم
        if data.startswith(
            "repetition_action:"
        ):

            await query.answer(
                "هذا الخيار لم يعد مستخدمًا.",
                show_alert=True
            )

        return

    parts = data.split(
        ":"
    )

    if len(parts) != 3:
        return

    action = parts[1]
    target_id_text = parts[2]

    if action not in (
        "mute",
        "restrict",
    ):

        return

    try:

        target_id = int(
            target_id_text
        )

    except (ValueError, TypeError):

        return

    # ==================================================
    # صلاحية من يختار العقوبة
    # ==================================================

    if not can_manage_repetition(
        actor.id,
        chat.id
    ):

        await query.answer(
            "❌ ليس لديك الصلاحية.",
            show_alert=True
        )

        return

    # ==================================================
    # تأكيد وجود الإنذارات
    # ==================================================

    try:

        warning_count = get_warning_count(
            chat.id,
            target_id
        )

    except Exception as e:

        print(
            "❌ خطأ في قراءة إنذارات المستخدم:",
            e
        )

        await query.answer(
            "❌ تعذر قراءة إنذارات المستخدم.",
            show_alert=True
        )

        return

    if warning_count < 3:

        await query.answer(
            "❌ لم يعد لديه 3 إنذارات.",
            show_alert=True
        )

        return

    # ==================================================
    # جلب المستخدم
    # ==================================================

    try:

        target = await context.bot.get_chat(
            target_id
        )

    except Exception:

        await query.answer(
            "❌ تعذر العثور على المستخدم.",
            show_alert=True
        )

        return

    # ==================================================
    # منع تطبيق العقوبة على رتبة أعلى/مساوية
    # ==================================================

    if target_id == OWNER_ID:

        await query.answer(
            "❌ لا يمكن تطبيق العقوبة على المطور الأساسي.",
            show_alert=True
        )

        return

    try:

        actor_level = get_rank_level(
            actor.id,
            chat.id
        )

        target_level = get_rank_level(
            target_id,
            chat.id
        )

    except Exception:

        actor_level = 0
        target_level = 0

    if target_level >= actor_level:

        await query.answer(
            "❌ لا يمكنك معاقبة شخص رتبته مساوية أو أعلى منك.",
            show_alert=True
        )

        return

    # ==================================================
    # مدة العقوبة
    # ==================================================

    settings = get_repetition_settings(
        chat.id
    )

    punishment_duration = settings[
        "punishment_duration"
    ]

    # ==================================================
    # تنفيذ العقوبة
    # ==================================================

    punished = await punish_user(
        update,
        context,
        target,
        action,
        punishment_duration
    )

    if not punished:

        await query.answer(
            "❌ تعذر تطبيق العقوبة.",
            show_alert=True
        )

        return

    # ==================================================
    # نجاح
    #
    # لا نمسح الإنذارات.
    # الإنذارات تبقى حتى يستخدم المشرف:
    # مسح انذاراته
    # ==================================================

    await query.answer(
        "تم اختيار العقوبة."
    )

    try:

        await query.edit_message_text(
            "• ✅ تم اختيار العقوبة المناسبة بنجاح ."
        )

    except Exception as e:

        print(
            "⚠️ خطأ في تعديل رسالة اختيار العقوبة:",
            e
        )


# ==================================================
# تفعيل التكرار
# ==================================================

async def enable_repetition(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    chat = update.effective_chat
    user = update.effective_user

    if not chat or not user:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    if not can_manage_repetition(
        user.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    update_repetition_setting(
        chat.id,
        "repetition_enabled",
        1
    )

    await update.message.reply_text(
        "✅ تم تفعيل حماية التكرار."
    )


# ==================================================
# تعطيل التكرار
# ==================================================

async def disable_repetition(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    chat = update.effective_chat
    user = update.effective_user

    if not chat or not user:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    if not can_manage_repetition(
        user.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    update_repetition_setting(
        chat.id,
        "repetition_enabled",
        0
    )

    reset_repetition_messages(
        chat.id,
        user.id
    )

    await update.message.reply_text(
        "✅ تم تعطيل حماية التكرار."
    )


# ==================================================
# بدء إعداد التكرار
#
# ضع تكرار 5
# ==================================================

async def set_repetition_start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    chat = update.effective_chat
    user = update.effective_user

    if not chat or not user:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    if not can_manage_repetition(
        user.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    text = (
        update.message.text or ""
    ).strip()

    parts = text.split()

    if len(parts) >= 3:

        try:

            limit = int(
                parts[2]
            )

        except (ValueError, TypeError):

            limit = 0

        if limit < 1:

            await update.message.reply_text(
                "❌ عدد التكرار يجب أن يكون 1 أو أكثر."
            )

            return

        repetition_sessions[
            (chat.id, user.id)
        ] = {
            "type": "repetition_duration",
            "limit": limit,
            "created_at": datetime.now(
                timezone.utc
            ),
        }

        await update.message.reply_text(
            "حسنًا، ارسل المدة التي تريدها ."
        )

        return

    await update.message.reply_text(
        "حسنًا، ارسل عدد التكرار أولًا.\n"
        "مثال:\n"
        "ضع تكرار 5"
    )


# ==================================================
# استقبال مدة التكرار
# ==================================================

async def receive_repetition_duration(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    user = update.effective_user
    chat = update.effective_chat

    if not user or not chat:
        return

    session_key = (
        chat.id,
        user.id
    )

    session = repetition_sessions.get(
        session_key
    )

    if not session:
        return

    if session.get(
        "type"
    ) != "repetition_duration":
        return

    text = (
        update.message.text or ""
    ).strip()

    command_like_patterns = (
        r"^تفعيل التكرار$",
        r"^تعطيل التكرار$",
        r"^ضع تكرار(?:\s+\d+)?$",
        r"^ضع رتبة التكرار\s+",
        r"^تغيير رتبة التكرار\s+",
        r"^مسح انذاراته",
    )

    for pattern in command_like_patterns:

        if re.match(
            pattern,
            text,
            flags=re.IGNORECASE
        ):

            return

    duration = parse_duration_token(
        text
    )

    if duration is None:

        await update.message.reply_text(
            "❌ المدة غير صحيحة.\n"
            "أمثلة: 3ث - 5د - 1س - 2ي"
        )

        return

    update_repetition_setting(
        chat.id,
        "repetition_limit",
        session["limit"]
    )

    update_repetition_setting(
        chat.id,
        "repetition_seconds",
        duration
    )

    repetition_sessions.pop(
        session_key,
        None
    )

    await update.message.reply_text(
        "✅ تم حفظ إعداد التكرار.\n\n"
        f"عدد الرسائل ↤︎ {session['limit']}\n"
        f"المدة ↤︎ {format_duration(duration)}"
    )


# ==================================================
# توافق مع main.py القديم
#
# الإنذارات لم تعد لها مدة.
# لذلك الأمر لا يغير أي شيء.
# ==================================================

async def set_warning_duration(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    return


# ==================================================
# توافق مع main.py القديم
#
# لم تعد هناك عقوبة تلقائية قابلة للتغيير.
# العقوبة تختار عند الإنذار الثالث.
# ==================================================

async def change_repetition_action(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    return


# ==================================================
# مدة كتم التكرار
#
# ضع كتم تكرار 10د
# ==================================================

async def set_mute_duration(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    await _set_punishment_duration(
        update,
        "mute"
    )


# ==================================================
# مدة تقييد التكرار
#
# ضع تقييد تكرار 10د
# ==================================================

async def set_restrict_duration(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    await _set_punishment_duration(
        update,
        "restrict"
    )


# ==================================================
# حفظ مدة العقوبة
# ==================================================

async def _set_punishment_duration(
    update,
    requested_action
):

    if not update.message:
        return

    chat = update.effective_chat
    user = update.effective_user

    if not chat or not user:
        return

    if not can_manage_repetition(
        user.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    text = (
        update.message.text or ""
    ).strip()

    parts = text.split()

    if len(parts) < 4:

        if requested_action == "mute":

            example = "ضع كتم تكرار 10د"

        else:

            example = "ضع تقييد تكرار 10د"

        await update.message.reply_text(
            "❌ المدة غير صحيحة.\n"
            f"مثال: {example}"
        )

        return

    duration = parse_duration_token(
        parts[-1]
    )

    if duration is None:

        await update.message.reply_text(
            "❌ المدة غير صحيحة."
        )

        return

    update_repetition_setting(
        chat.id,
        "repetition_punishment_duration",
        duration
    )

    await update.message.reply_text(
        "✅ تم تعيين مدة العقوبة إلى "
        f"{format_duration(duration)}."
    )


# ==================================================
# رتبة التكرار
# ==================================================

async def set_repetition_rank(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    chat = update.effective_chat
    user = update.effective_user

    if not chat or not user:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    if not can_manage_repetition(
        user.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    text = (
        update.message.text or ""
    ).strip()

    match = re.match(
        r"^(?:ضع|تغيير)\s+رتبة\s+التكرار\s+(.+?)\s*$",
        text,
        flags=re.IGNORECASE
    )

    if not match:

        await update.message.reply_text(
            "❌ اختر رتبة التكرار.\n"
            "مثال:\n"
            "ضع رتبة التكرار المالك"
        )

        return

    rank = match.group(1).strip()

    rank_aliases = {
        "عضو": "عضو",
        "مميز": "مميز",
        "ادمن": "ادمن",
        "أدمن": "ادمن",
        "ادمن اساسي": "ادمن اساسي",
        "أدمن اساسي": "ادمن اساسي",
        "أدمن أساسي": "ادمن اساسي",
        "ادمن أساسي": "ادمن اساسي",
        "نائب المالك": "نائب المالك",
        "المالك": "المالك",
        "Dev": "Dev",
        "dev": "Dev",
    }

    rank = rank_aliases.get(
        rank,
        rank
    )

    allowed_ranks = (
        "عضو",
        "مميز",
        "ادمن",
        "ادمن اساسي",
        "نائب المالك",
        "المالك",
        "Dev",
    )

    if rank not in allowed_ranks:

        await update.message.reply_text(
            "❌ الرتب المتاحة:\n"
            "عضو\n"
            "مميز\n"
            "ادمن\n"
            "ادمن اساسي\n"
            "نائب المالك\n"
            "المالك\n"
            "Dev"
        )

        return

    update_repetition_setting(
        chat.id,
        "repetition_rank",
        rank
    )

    await update.message.reply_text(
        f"☑️ تم تعيين رتبة التكرار إلى {rank}."
    )


# ==================================================
# جلب الهدف لمسح الإنذارات
# ==================================================

async def _get_warning_target(
    update,
    context
):

    if not update.message:
        return None

    # --------------------------------------------------
    # بالرد
    # --------------------------------------------------

    if update.message.reply_to_message:

        target = (
            update.message.reply_to_message.from_user
        )

        if target:
            return target

    # --------------------------------------------------
    # بالآيدي أو username
    # --------------------------------------------------

    text = (
        update.message.text or ""
    ).strip()

    parts = text.split()

    for value in parts[2:]:

        value = value.strip()

        if value.isdigit():

            try:

                return await context.bot.get_chat(
                    int(value)
                )

            except Exception:

                continue

        if value.startswith("@"):

            try:

                return await context.bot.get_chat(
                    value
                )

            except Exception:

                continue

    return None


# ==================================================
# مسح انذاراته
#
# بالرد
# أو ID
# أو username
# ==================================================

async def clear_user_repetition_warnings(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    if not update.message:
        return

    chat = update.effective_chat
    actor = update.effective_user

    if not chat or not actor:
        return

    if chat.type not in (
        "group",
        "supergroup"
    ):
        return

    if not can_manage_repetition(
        actor.id,
        chat.id
    ):

        await update.message.reply_text(
            "❌ هذا الأمر للادمن الاساسي وفوق فقط."
        )

        return

    target = await _get_warning_target(
        update,
        context
    )

    if not target:

        await update.message.reply_text(
            "❌ استخدم الأمر بالرد على الشخص أو بالآيدي أو باليوزر."
        )

        return

    # ==================================================
    # مسح جميع الإنذارات
    #
    # اليدوية + التكرار
    # ==================================================

    deleted = clear_warnings(
        chat.id,
        target.id
    )

    # ==================================================
    # تصفير عداد التكرار
    # ==================================================

    reset_repetition_messages(
        chat.id,
        target.id
    )

    if deleted:

        await update.message.reply_text(
            "☑️ تم مسح جميع انذاراته."
        )

    else:

        await update.message.reply_text(
            "• الشخص هذا ماعنده انذارات من قبل."
        )


# ==================================================
# تنظيف جلسات الإعداد القديمة
# ==================================================

async def cleanup_repetition_sessions():

    while True:

        try:

            now = datetime.now(
                timezone.utc
            )

            expired_keys = []

            for key, session in list(
                repetition_sessions.items()
            ):

                created_at = session.get(
                    "created_at"
                )

                if not created_at:
                    continue

                if (
                    now - created_at
                ).total_seconds() > 300:

                    expired_keys.append(
                        key
                    )

            for key in expired_keys:

                repetition_sessions.pop(
                    key,
                    None
                )

        except Exception as e:

            print(
                "⚠️ خطأ في تنظيف جلسات التكرار:",
                e
            )

        await asyncio.sleep(
            60
        )


# ==================================================
# الحلقة الخلفية
#
# لم يعد هناك تنظيف لإنذارات منتهية،
# لأن الإنذارات أصبحت دائمة.
#
# تبقى الدالة موجودة حتى لا ينكسر main.py.
# ==================================================

async def repetition_expiry_loop(
    application
):

    try:

        application.create_task(
            cleanup_repetition_sessions()
        )

    except Exception as e:

        print(
            "⚠️ تعذر تشغيل جلسات التكرار:",
            e
        )

    # --------------------------------------------------
    # الحلقة تبقى فقط للمحافظة على تشغيل المهمة
    # ولا تحذف أي إنذارات.
    # --------------------------------------------------

    while True:

        await asyncio.sleep(
            60
        )
